/* The following code was generated by JFlex 1.4.1 on 22/02/14 17:23 */

// ************  Imports and packages ********************

package lexic;
import syntax.Parser;

@SuppressWarnings({"unused" })


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 22/02/14 17:23 from the specification file
 * <tt>./src/lexic/lexic.flex</tt>
 */
public class Lexic {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\26\1\13\1\0\1\26\1\23\22\0\1\26\1\46\4\0"+
    "\1\47\1\4\1\53\1\53\1\3\1\25\1\53\1\25\1\12\1\2"+
    "\12\22\1\0\1\53\1\51\1\45\1\52\2\0\4\1\1\24\3\1"+
    "\1\16\2\1\1\15\1\1\1\20\5\1\1\17\6\1\1\53\1\5"+
    "\1\53\3\0\1\31\1\35\1\27\1\32\1\37\1\10\1\1\1\30"+
    "\1\41\2\1\1\36\1\42\1\6\1\33\2\1\1\11\1\40\1\7"+
    "\1\34\1\44\1\43\3\1\1\14\1\50\1\21\u7305\0\1\1\u8c79\0"+
    "\1\1\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\3\3\1\2\1\4\1\3\1\5"+
    "\1\4\10\2\2\3\4\1\4\0\1\2\1\0\1\6"+
    "\1\0\5\2\1\7\4\2\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\4\1\0\1\16\1\0\2\2\1\0"+
    "\2\6\4\2\1\17\4\2\1\20\1\2\1\21\1\0"+
    "\1\22\1\2\1\23\1\2\1\24\2\2\1\25\1\2"+
    "\1\0\2\2\1\26\1\27\1\30\1\0\1\31\1\32"+
    "\1\0\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[91];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\54\0\260\0\334\0\54"+
    "\0\u0108\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c"+
    "\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c"+
    "\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8\0\u0604\0\130\0\u0630"+
    "\0\u065c\0\u0688\0\u06b4\0\54\0\54\0\54\0\54\0\54"+
    "\0\54\0\u03f4\0\u06e0\0\54\0\u070c\0\u0738\0\u0764\0\u0790"+
    "\0\u07bc\0\u0528\0\u07e8\0\u0814\0\u0840\0\u086c\0\130\0\u0898"+
    "\0\u08c4\0\u08f0\0\u091c\0\54\0\u0948\0\130\0\u0974\0\130"+
    "\0\u09a0\0\130\0\u09cc\0\130\0\u09f8\0\u0a24\0\130\0\u0a50"+
    "\0\u0a7c\0\u0aa8\0\u0ad4\0\130\0\130\0\130\0\u0b00\0\130"+
    "\0\130\0\u0b2c\0\54";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[91];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\3\3\1\7"+
    "\1\5\1\10\1\11\4\3\1\5\1\12\1\13\1\3"+
    "\1\5\1\10\1\14\2\3\1\15\4\3\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\5\55\0\1\3\4\0\4\3\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\16\3\11\0"+
    "\1\32\1\33\51\0\1\34\3\0\1\35\4\34\3\0"+
    "\4\34\3\0\1\34\2\0\16\34\10\0\1\3\4\0"+
    "\4\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\10\3\1\36\5\3\24\0\1\37\50\0\1\40\7\0"+
    "\1\12\1\0\1\41\12\0\1\41\27\0\1\10\41\0"+
    "\1\3\4\0\4\3\3\0\4\3\1\0\1\3\1\0"+
    "\1\3\2\0\1\3\1\42\14\3\10\0\1\3\4\0"+
    "\4\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\4\3\1\43\11\3\10\0\1\3\4\0\4\3\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\7\3\1\44"+
    "\6\3\10\0\1\3\4\0\1\3\1\45\2\3\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\16\3\10\0"+
    "\1\3\4\0\1\46\1\3\1\47\1\3\3\0\4\3"+
    "\1\0\1\3\1\0\1\3\2\0\16\3\10\0\1\3"+
    "\4\0\4\3\3\0\4\3\1\0\1\3\1\0\1\3"+
    "\2\0\2\3\1\50\13\3\10\0\1\3\4\0\3\3"+
    "\1\51\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\1\3\1\52\14\3\10\0\1\3\4\0\4\3\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\4\3\1\53"+
    "\11\3\54\0\1\54\53\0\1\55\55\0\1\56\54\0"+
    "\1\57\50\0\1\60\53\0\1\61\6\0\13\32\1\10"+
    "\7\32\1\62\30\32\3\33\1\63\50\33\4\0\1\64"+
    "\55\0\4\65\43\0\1\3\4\0\1\3\1\66\2\3"+
    "\3\0\4\3\1\0\1\3\1\0\1\3\2\0\2\3"+
    "\1\67\13\3\25\0\1\70\57\0\1\40\1\0\1\71"+
    "\12\0\1\71\36\0\1\72\32\0\1\3\4\0\4\3"+
    "\3\0\4\3\1\0\1\3\1\0\1\3\2\0\2\3"+
    "\1\73\13\3\10\0\1\3\4\0\4\3\3\0\4\3"+
    "\1\0\1\3\1\0\1\3\2\0\5\3\1\74\10\3"+
    "\10\0\1\3\4\0\4\3\3\0\4\3\1\0\1\3"+
    "\1\0\1\3\2\0\11\3\1\75\4\3\10\0\1\3"+
    "\4\0\3\3\1\76\3\0\4\3\1\0\1\3\1\0"+
    "\1\3\2\0\16\3\10\0\1\3\4\0\1\3\1\77"+
    "\2\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\16\3\10\0\1\3\4\0\4\3\3\0\4\3\1\0"+
    "\1\3\1\0\1\3\2\0\12\3\1\100\3\3\10\0"+
    "\1\3\4\0\4\3\3\0\4\3\1\0\1\3\1\0"+
    "\1\3\2\0\12\3\1\101\3\3\10\0\1\3\4\0"+
    "\4\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\12\3\1\102\3\3\10\0\1\3\4\0\4\3\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\12\3\1\103"+
    "\3\3\7\0\2\33\1\10\1\63\50\33\4\0\1\104"+
    "\50\0\1\3\4\0\4\3\3\0\4\3\1\0\1\3"+
    "\1\0\1\3\2\0\5\3\1\105\10\3\10\0\1\3"+
    "\4\0\4\3\3\0\4\3\1\0\1\3\1\0\1\3"+
    "\2\0\3\3\1\106\12\3\26\0\1\107\56\0\1\72"+
    "\2\0\1\72\27\0\1\3\4\0\3\3\1\110\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\16\3\10\0"+
    "\1\3\4\0\4\3\3\0\4\3\1\0\1\3\1\0"+
    "\1\3\2\0\6\3\1\111\7\3\10\0\1\3\4\0"+
    "\4\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\10\3\1\112\5\3\10\0\1\3\4\0\4\3\3\0"+
    "\4\3\1\0\1\3\1\0\1\3\2\0\5\3\1\113"+
    "\10\3\10\0\1\3\4\0\1\114\3\3\3\0\4\3"+
    "\1\0\1\3\1\0\1\3\2\0\16\3\10\0\1\3"+
    "\4\0\1\3\1\115\2\3\3\0\4\3\1\0\1\3"+
    "\1\0\1\3\2\0\16\3\10\0\1\3\4\0\4\3"+
    "\3\0\4\3\1\0\1\3\1\0\1\3\2\0\7\3"+
    "\1\116\6\3\10\0\1\3\4\0\4\3\3\0\4\3"+
    "\1\0\1\3\1\0\1\3\2\0\3\3\1\117\12\3"+
    "\10\0\1\3\4\0\3\3\1\120\3\0\4\3\1\0"+
    "\1\3\1\0\1\3\2\0\16\3\25\0\1\121\36\0"+
    "\1\3\4\0\4\3\3\0\4\3\1\0\1\3\1\0"+
    "\1\3\2\0\7\3\1\122\6\3\10\0\1\3\4\0"+
    "\4\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\1\123\15\3\10\0\1\3\4\0\4\3\3\0\4\3"+
    "\1\0\1\3\1\0\1\3\2\0\10\3\1\124\5\3"+
    "\10\0\1\3\4\0\4\3\3\0\4\3\1\0\1\3"+
    "\1\0\1\3\2\0\10\3\1\125\5\3\10\0\1\3"+
    "\4\0\1\126\3\3\3\0\4\3\1\0\1\3\1\0"+
    "\1\3\2\0\16\3\27\0\1\127\34\0\1\3\4\0"+
    "\4\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\10\3\1\130\5\3\10\0\1\3\4\0\1\3\1\131"+
    "\2\3\3\0\4\3\1\0\1\3\1\0\1\3\2\0"+
    "\16\3\26\0\1\132\55\0\1\133\32\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2904];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\2\1\1\11\21\1\4\0"+
    "\1\1\1\0\1\1\1\0\12\1\6\11\1\1\1\0"+
    "\1\11\1\0\2\1\1\0\13\1\1\11\2\1\1\0"+
    "\11\1\1\0\5\1\1\0\2\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[91];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
// ************  Attributes and methods ********************

private Parser parser;

public void setParser(Parser parser) {
	this.parser=parser;
}

// * Getter method of line generated attribute by JFlex.
public int getLine() { 
	// * Flex empieza en cero
	return yyline+1;
}

// Getter method of column generated attribute by JFlex.
public int getColumn() { 
	// * Flex empieza en cero
	return yycolumn+1;
}



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexic(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexic(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 9: 
          { parser.setYylval(yytext()); return Parser.DISTINTO;
          }
        case 28: break;
        case 14: 
          { parser.setYylval(yycharat(1)); return Parser.CTE_CARACTER;
          }
        case 29: break;
        case 16: 
          { parser.setYylval(yytext()); return Parser.CTE_CARACTER;
          }
        case 30: break;
        case 6: 
          { parser.setYylval(new Double(yytext())); return Parser.CTE_REAL;
          }
        case 31: break;
        case 3: 
          { parser.setYylval(yytext()); return yycharat(0);
          }
        case 32: break;
        case 11: 
          { parser.setYylval(yytext()); return Parser.O;
          }
        case 33: break;
        case 13: 
          { parser.setYylval(yytext()); return Parser.MAYORIGUAL;
          }
        case 34: break;
        case 23: 
          { parser.setYylval(yytext()); return Parser.WHILE;
          }
        case 35: break;
        case 18: 
          { parser.setYylval(yytext()); return Parser.CHAR;
          }
        case 36: break;
        case 24: 
          { parser.setYylval(yytext()); return Parser.RETURN;
          }
        case 37: break;
        case 17: 
          { parser.setYylval(yytext()); return Parser.READ;
          }
        case 38: break;
        case 27: 
          { parser.setYylval(new Integer(yytext())); return Parser.CTE_CARACTER;
          }
        case 39: break;
        case 5: 
          { parser.setYylval(new Integer(yytext())); return Parser.CTE_ENTERA;
          }
        case 40: break;
        case 7: 
          { parser.setYylval(yytext()); return Parser.IF;
          }
        case 41: break;
        case 20: 
          { parser.setYylval(yytext()); return Parser.MAIN;
          }
        case 42: break;
        case 12: 
          { parser.setYylval(yytext()); return Parser.MENORIGUAL;
          }
        case 43: break;
        case 1: 
          { System.out.println("Unexpected char at (line: " + this.getLine()+ ", column: " + this.getColumn() + "): '" + yycharat(0) + "'.");
          }
        case 44: break;
        case 10: 
          { parser.setYylval(yytext()); return Parser.Y;
          }
        case 45: break;
        case 19: 
          { parser.setYylval(yytext()); return Parser.ELSE;
          }
        case 46: break;
        case 15: 
          { parser.setYylval(yytext()); return Parser.INT;
          }
        case 47: break;
        case 26: 
          { parser.setYylval(yytext()); return Parser.STRUCT;
          }
        case 48: break;
        case 21: 
          { parser.setYylval(yytext()); return Parser.VOID;
          }
        case 49: break;
        case 2: 
          { parser.setYylval(yytext()); return Parser.ID;
          }
        case 50: break;
        case 22: 
          { parser.setYylval(yytext()); return Parser.WRITE;
          }
        case 51: break;
        case 25: 
          { parser.setYylval(yytext()); return Parser.DOUBLE;
          }
        case 52: break;
        case 4: 
          { 
          }
        case 53: break;
        case 8: 
          { parser.setYylval(yytext()); return Parser.IGUALDAD;
          }
        case 54: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
